[package]
name = "rust"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Rust Variable Example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "2.2.0"
serde_json = "1.0.114"

[workspace]
