spin_manifest_version = 2

[application]
name = "go"
version = "0.1.0"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = "Go"


[variables]
token = { required = true }
api_uri = { default = "http://localhost:3001" }

[[trigger.http]]
route = "/..."
component = "go"

[component.go]
source = "main.wasm"
allowed_outbound_hosts = ["{{ api_uri }}"]
[component.go.variables]
token = "{{ token }}"
api_uri = "{{ api_uri }}"
version = "v1"
[component.go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
